### Register New User
POST http://localhost:8080/api/accounts

Content-Type: application/json
{
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "admin"
}
###
# Login with admin credentials
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###
# Get user profile - requires JWT token
GET http://localhost:8080/api/accounts/profile
Authorization: Bearer {{auth_token}}

HTTP/1.1 403  - Forbidden
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
content-length: 0
date: Fri, 29 Nov 2024 19:16:22 GMT
connection: close